---
title: "biyoinformatik"
output: html_document
date: '2022-05-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load required library
library("ape")
```

```{r}
# Download gene sequences from GenBank (NCBI) for 5 species
homosapiens <- read.GenBank("NM_003381.4", as.character = "TRUE")
pongoapelii <- read.GenBank("XM_024248829.1", as.character = "TRUE")
equuscaballus <- read.GenBank("XM_023633005.1", as.character = "TRUE")
lutralutra <- read.GenBank("XM_047733983.1", as.character = "TRUE")
caviaporcellus <- read.GenBank("XM_005003122.3", as.character = "TRUE")
```

```{r}
# Convert sequences to single-character strings
seq1 = paste(homosapiens, collapse="")
seq2 = paste(pongoapelii, collapse="")
seq3 = paste(equuscaballus, collapse="")
seq4 = paste(lutralutra, collapse="")
seq5 = paste(caviaporcellus, collapse="")
```

```{r}
# Load Biostrings for sequence alignment
library("Biostrings")
```

```{r}
# Pairwise alignments: Homo sapiens vs Pongo abelii
a1<-pairwiseAlignment(pattern=seq1, subject=seq2, type="local")
a1

a1.1<-pairwiseAlignment(pattern = seq1, subject = seq2, type="global")
a1.1
```

```{r}
# Homo sapiens vs Equus caballus
a2<-pairwiseAlignment(pattern = seq1, subject = seq3, type="local")
a2

a2.1<-pairwiseAlignment(pattern = seq1, subject = seq3, type="global")
a2.1
```

```{r}
# Homo sapiens vs Lutra lutra
a3<-pairwiseAlignment(pattern = seq1, subject = seq4, type="local")
a3

a3.1<-pairwiseAlignment(pattern = seq1, subject = seq4, type="global")
a3.1
```

```{r}
# Homo sapiens vs Cavia porcellus
a4<- pairwiseAlignment(pattern = seq1, subject = seq5, type="local")
a4

a4.1<- pairwiseAlignment(pattern = seq1, subject = seq5, type="global")
a4.1
```

```{r}
# Interpretation:
# Based on the alignment scores:
# - The most similar species to Homo sapiens is Pongo abelii (orangutan).
# - The most different species in sequence is Cavia porcellus (guinea pig).
```
